#!/usr/bin/env python3
"""
Rebuild knowledge/index.yaml by scanning knowledge/*/source.yaml.

This is a write-after hook called by book-to-knowledge (Step 10b) after a
knowledge base is created or updated.  It aggregates all source metadata in
KNOWLEDGE_ROOT into a single index file for efficient query by book-knowledge.

Usage:
    python rebuild_knowledge_index.py                     # uses KNOWLEDGE_ROOT or ./knowledge
    python rebuild_knowledge_index.py --knowledge-root /path/to/knowledge

Exit codes:
    0  — index rebuilt (or nothing to do, no knowledge dirs found)
    1  — error
"""

import argparse
import os
import sys
from pathlib import Path

# ── I/O ──────────────────────────────────────────────────────────────────────

# Force UTF-8 on Windows consoles that default to legacy code pages.
for _stream in (sys.stdout, sysderr := sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass


def _resolve_knowledge_root() -> Path:
    """Determine KNOWLEDGE_ROOT: env var > default ./knowledge."""
    raw = os.environ.get("KNOWLEDGE_ROOT") or "./knowledge"
    p = Path(raw)
    return p.resolve() if p.is_absolute() else Path.cwd() / p


# ── Scan ─────────────────────────────────────────────────────────────────────


def scan_knowledge_bases(knowledge_root: Path) -> list[dict]:
    """Scan knowledge/*/source.yaml and return a sorted list of metadata dicts."""
    entries: list[dict] = []
    if not knowledge_root.is_dir():
        return entries

    for child in sorted(knowledge_root.iterdir()):
        source_yaml = child / "source.yaml"
        if not source_yaml.is_file():
            continue
        slug = child.name
        meta = _parse_source_yaml(source_yaml, slug)
        if meta is not None:
            entries.append(meta)

    return entries


def _parse_source_yaml(path: Path, slug: str) -> dict | None:
    """Minimal YAML parser that reads only the fields we need.

    We avoid pulling in PyYAML as a dependency.  The source.yaml format is
    simple enough to parse with basic string operations.
    """
    meta: dict[str, str | list[str] | int | None] = {
        "slug": slug,
        "title": None,
        "author": None,
        "source_format": None,
        "word_count": None,
        "chapter_count": None,
        "generated_date": None,
        "tags": [],
        "content_type": None,
    }

    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return None  # skip unreadable files

    for line in text.splitlines():
        stripped = line.strip()
        # skip comments and empty lines
        if not stripped or stripped.startswith("#"):
            continue
        # skip list items (they belong to tags)
        if stripped.startswith("- "):
            tag = stripped[2:].strip().strip('"').strip("'")
            if tag:
                existing = meta.setdefault("tags", [])
                if isinstance(existing, list):
                    existing.append(tag)
            continue
        # key: value  (simple scalar, no nesting)
        if ": " not in stripped:
            continue
        key, _, raw_val = stripped.partition(": ")
        key = key.strip()
        val = raw_val.strip().strip('"').strip("'")

        if key in ("title", "author", "source_format", "generated_date", "slug", "content_type"):
            meta[key] = val
        elif key == "word_count":
            try:
                meta["word_count"] = int(val)
            except ValueError:
                meta["word_count"] = None
        elif key == "chapter_count":
            try:
                meta["chapter_count"] = int(val)
            except ValueError:
                meta["chapter_count"] = None

    return meta


# ── Generate index.yaml ──────────────────────────────────────────────────────


def generate_index_yaml(entries: list[dict], knowledge_root: Path) -> str:
    """Produce the content for index.yaml."""
    lines: list[str] = [
        "# knowledge/index.yaml — auto-generated by rebuild_knowledge_index.py",
        "# Do not edit manually; run the rebuild script after adding/removing knowledge bases.",
        "---",
        f"knowledge_root: \"{knowledge_root.as_posix()}\"",
        f"entry_count: {len(entries)}",
        "entries:",
    ]

    for entry in entries:
        slug = entry.get("slug", "unknown")
        title = entry.get("title") or slug
        author = entry.get("author") or "Unknown"
        fmt = entry.get("source_format") or "-"
        wc = entry.get("word_count")
        cc = entry.get("chapter_count")
        tags = entry.get("tags") or []
        generated = entry.get("generated_date") or "-"
        content_type = entry.get("content_type") or "text"
        tags_str = ", ".join(tags)

        lines.append(f"  - slug: \"{slug}\"")
        lines.append(f"    title: \"{title}\"")
        lines.append(f"    author: \"{author}\"")
        lines.append(f"    source_format: \"{fmt}\"")
        lines.append(f"    word_count: {wc if wc is not None else 0}")
        lines.append(f"    chapter_count: {cc if cc is not None else 0}")
        lines.append(f"    generated_date: \"{generated}\"")
        lines.append(f"    tags: [{tags_str}]")
        lines.append(f"    content_type: \"{content_type}\"")
        lines.append("")

    return "\n".join(lines)


def write_index(index_content: str, knowledge_root: Path) -> None:
    """Write index.yaml atomically."""
    dest = knowledge_root / "index.yaml"
    tmp = dest.with_suffix(".yaml.tmp")
    try:
        tmp.write_text(index_content, encoding="utf-8")
        tmp.replace(dest)
    finally:
        if tmp.exists():
            tmp.unlink(missing_ok=True)


# ── CLI ──────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Rebuild knowledge/index.yaml from knowledge/*/source.yaml",
    )
    parser.add_argument(
        "--knowledge-root",
        default=None,
        help="Path to the knowledge root (default: $KNOWLEDGE_ROOT or ./knowledge)",
    )
    args = parser.parse_args()

    knowledge_root = (
        Path(args.knowledge_root).resolve()
        if args.knowledge_root
        else _resolve_knowledge_root()
    )

    print(f"📂 Scanning {knowledge_root} ...", file=sys.stdout)
    entries = scan_knowledge_bases(knowledge_root)

    if not entries:
        print(f"⚠ No knowledge bases found under {knowledge_root}.", file=sys.stdout)

    content = generate_index_yaml(entries, knowledge_root)
    write_index(content, knowledge_root)

    count = len(entries)
    print(f"✅ Rebuilt {knowledge_root / 'index.yaml'} ({count} entr{'y' if count == 1 else 'ies'}).", file=sys.stdout)


if __name__ == "__main__":
    main()
